Project structure
nfqakademija/imk pull request #1
Opened 2017-04-12 17:06 UTC by karmrt

Basic routes and controllers

2017-04-12 17:12 UTC, pauliusrum commented on src/AppBundle/Controller/AdminController.php
> +        //naudotojo redagavimas
Komentuok angliškai :)

2017-04-12 17:13 UTC, pauliusrum commented on src/AppBundle/Controller/AccountsController.php
> +        return $this->render('AppBundle:Accounts:login.html.twig', array(// ...
Naudok `[]` vietoj `array()`

2017-04-12 17:17 UTC, pauliusrum commented on src/AppBundle/Controller/HomeController.php
> +        return new Response('Balsuojam uz decision nr. : ' . $decisionId .
Čia turbūt reiks JsonResponse, kad front end'as žinotų ar sėkminga operacija.

2017-04-12 17:23 UTC, pauliusrum requested changes
`Array()` sintaksė yra pasenusi ir jos reiktų nenaudoti, naudok `[]`.

Komentuokite angliškai, nes jeigu prie projekto prisijunks užsienietis programuotojas jis nieko nesupras :)

2017-04-12 18:37 UTC, pauliusrum approved these changes
+1, būtų gerai, kad dar kolegos taip pat peržiūrėtų.

2017-04-13 08:58 UTC, ghost approved these changes

2017-04-13 11:59 UTC, ievadap approved these changes

2017-04-13 14:01 UTC, merged